### ISSUE TITLE
Support nested jshint configurations

### ISSUE THREAD

**Issue by artursmirnov** [Microsoft/vscode-jshint#13]
My application has main `.jshintrc` configuration in root folder, which works just fine. But for tests there is another configuration located at `tests/.jshintrc` that has a lot of `predef`s for test helpers. And the extension ignores tests configuration and applies the main one. 

The case is common for most Ember CLI apps.

**Comment by jaysylvester** [comment]
I have a project-level `.jshintrc` file and then a couple more sprinkled throughout that extend the project config. The project config handles basic formatting that I want to apply to all JS files, and the nested files handle different parts of the app (node.js server-side vs front end static library, which have different `browser`, `node`, and `predef` settings).

This workflow works in other editors, so I'd love to see it in VS Code.

**Comment by edwin177** [comment]
+1
