### ISSUE TITLE
How to ignore some folders

### ISSUE THREAD

**Issue by g-adolph** [Microsoft/vscode-jshint#14]
How can i ignore folders like `node_modules` and `bower_components` from my jshint check?

we can use something like jsconfig.json exclude paths. Is a bad idea?

**Comment by kieferrm** [comment]
With bd489b92daf1d3d747dcd21128ca0cb88715bae3 you can now specify files and folders in the user or in the workspace settings that should be ignored by jshint. I created #22 and #23 to cover the full scope of jshint exclude support.
