### ISSUE TITLE
jshint does not recognize typings (.tsd) configurations for node

### ISSUE THREAD

**Issue by appeality** [Microsoft/vscode-jshint#15]
When using node in VS Code, jshint does not recognize the built in Node types/funcs, such as __dir name, require, etc. This results in erroneous linting errors. Note that VS Code does not recognize these types until the node tsd files are added to a project. 

Is there a workaround for this?

**Comment by rkhat** [comment]
Add `"node": true` as a jshint option

**Comment by kieferrm** [comment]
@appeality @rkhat's should solve your 'erroneous listing errors' issues.
