### ISSUE TITLE
Failed to load jshint library

### ISSUE THREAD

**Issue by jsnjack** [Microsoft/vscode-jshint#16]
I have just updated to the version 0.10.10. When I open javascript file, I got an error that says "Failed to load jshint library. Please install it...". I have jshint package installed globally with command `npm install -g jshint`. My output from terminal:

``` bash
22:12 $ jshint -v
jshint v2.9.1
```

I'm on Fedora 23, jshint 2.9.1, vscode 0.10.10, jshint extension has version 0.10.6

**Comment by jsnjack** [comment]
It didn't work because of the bad npm configuration in my system. `npm config get prefix` returned `/usr/local/`, however all node modules were installed with `/usr` prefix

**Comment by colek42** [comment]
thank you @jsnjack
