### ISSUE TITLE
Can not install extension anymore

### ISSUE THREAD

**Issue by tbuschto** [Microsoft/vscode-jshint#17]
I had some strange VSCode behavior, so I re-installed everything. Now I can't install the jshint extension anymore. This is what I do:

`ext install jshint` -> "'jshint' was successfully installed. Restart to enable it."

After the restart:
`ext` -> Lists installed extensions, does not include jshint

Other extensions install fine (e.g. PowerShell). I have the global npm jshint module installed.

Visual Studio Code: 0.10.10 (after re-install, was something older before)
OS: Windows 10 Pro
Node: 4.1.1

**Comment by kieferrm** [comment]
@tbuschto Pls try the following:
1. close vscode
2. go to your home directory
3. go into .vscode/extensions
4. completely delete dbaeumer.jshint-0.10.x
5. restart vscode
6. install jshint extension

I'm guessing that the installation process had an issue. Or there were leftovers from a previous uninstall of the extension and thus the install assumed the extension was already installed. Either way it seems the activation of the extension fails. 

Pls reopen if you still have the issue.
