### ISSUE TITLE
Clarify documentation on the config options

### ISSUE THREAD

**Issue by egamma** [Microsoft/vscode-jshint#19]
>Configuration Options
jshint.options: an option bag as defined by the JSHint API here. Defaults to an empty option bag.

I suggest that the guidance is that the jshint.options is used to configure how to options for starting jshint through the CLI. Users should use the .jshintrc for defining jshint options.

**Comment by kieferrm** [comment]
The doc clearly needs to be more explicit. However, the current behavior is a natural extension of how the jshint cli behaves (http://jshint.com/docs/cli/) 

> jshint will look for this configuration in a number of locations, stopping at the first positive match:
> 
> 1. The location specified with the --config flag
> 2. A file named package.json located in the current directory or any parent of the current directory (the configuration should be declared as the jshintConfig attribute of that file's JSON value)
> 3. A file named .jshintrc located in the current directory or any parent of the current directory
> 4. A file named .jshintrc located in the current user's "home" directory (where defined)


The extension is doing the following:

1. The location specified in jshint.options.config
2. A file named package.json located in the current directory or any parent of the current directory (the configuration should be declared as the jshintConfig attribute of that file's JSON value)
3. A file named .jshintrc located in the current directory or any parent of the current directory
4. A file named .jshintrc located in the current user's "home" directory (where defined)
5. The options specified in jshint.options either in workspace settings or the user settings.
