### ISSUE TITLE
Gallery banner is too dark

### ISSUE THREAD

**Issue by gregvanl** [Microsoft/vscode-jshint#2]
Who turned out the lights?
The gallery banner for the JSHint Marketplace page is very dark and it is difficult to read the text.

**Comment by dbaeumer** [comment]
@gregvanl I followed your advice with the icon and the color. It is right now:

```json
	"icon": "jshint_icon.png",
	"galleryBanner": {
		"color": "#2e2e2d"
	}
```
Any advice

**Comment by mikkotikkanen** [comment]
still dark to me. +1

**Comment by gregvanl** [comment]
I think you need to set the gallerybanner theme to dark to get light text.

	"galleryBanner": {
		"color": "#5c2d91",
		"theme": "dark"
         }

**Comment by dbaeumer** [comment]
Made the suggested changes and re-published the extension.
