### ISSUE TITLE
'extends' and 'exclude' should show up in .jshintrc intellisense

### ISSUE THREAD

**Issue by kieferrm** [Microsoft/vscode-jshint#26]
Use intellisense in .jshintrc. There are no proposals for 'extends' or 'exclude'.

**Comment by Xenya0815** [comment]
What's the status of `extends` support?

**Comment by RMacfarlane** [comment]
`extends` is supported within a .jshintrc file, there is just no suggestion for it

**Comment by RMacfarlane** [comment]
Updated .jshintrc schema [here](https://github.com/SchemaStore/schemastore/pull/391) to include 'extends'. 'exclude' doesn't appear to be a supported option for .jshintrc

'extends' now shown as a proposal when editing .jshintrc files
