### ISSUE TITLE
VScode unable to recognize whether JShint extension is installed or not.

### ISSUE THREAD

**Issue by v-pavanp** [Microsoft/vscode-jshint#33]
- VSCode Version:1.1.0-alpha
- OS Version: Windows10

Steps to Reproduce:
1. Launch app and try to install JShint extension.
2. Verify user should get success message or error message.
3. If user gets error me message then reload app manually.

Actual:
1. I observed after reloading app, JShint extension started showing up in both extension install and installed list. 

Expected:
1. if there is no update for the extension then it should not display under install list.
2. If extension is not installed then it should not display in the installed extensions list.

Getting error message like below:
![image](https://cloud.githubusercontent.com/assets/17735796/15089227/e0560132-13b3-11e6-81f5-9007bdbf6b2d.png)

Extension install list:
![image](https://cloud.githubusercontent.com/assets/17735796/15089181/1a8fa034-13b3-11e6-8f2a-68eb2fbc60f7.png)

Extension Installed List:

![image](https://cloud.githubusercontent.com/assets/17735796/15089197/5ffab2f8-13b3-11e6-9da8-eb615e8b12d1.png)

Verification steps after reloading window manually:

![jshintextensionshowingboththeplaces](https://cloud.githubusercontent.com/assets/17735796/15089669/bbbbe788-13bd-11e6-8071-07dba267dc75.gif)

**Comment by RMacfarlane** [comment]
Issue with VSCode, not extension. Has been fixed in VSCode
