### ISSUE TITLE
Report warning as errors, warnings do not standout

### ISSUE THREAD

**Issue by lucdew** [Microsoft/vscode-jshint#37]
Hi,
it would be interesting to be able to report warning as errors or choose the color for warnings.
Currently warnings are reported by default in visual studio code and it is not really visible, they do not standout. At the company I work for, code pushes with jshint warnings are rejected.

For example it would be interesting to have a property:
**jshint.warning.reportAsError=true**

**Comment by RMacfarlane** [comment]
This has been added as **jshint.reportWarningsAsErrors** in version 0.10.16
