### ISSUE TITLE
The version of jshint is out of date.

### ISSUE THREAD

**Issue by icezohu** [Microsoft/vscode-jshint#38]
The version of jshint is out of date and could not recognize many of the es6 grammars. And there are a lot of error messages which are really disturbing. Please could you help update to the latest version? Thank you very much!

**Comment by poumian** [comment]
I'm also having this same problem. I have included the following configuration in my Workplace settings file and I still see a bunch of JSHint errors in ES6:

`  "jshint.options": {
        "esversion": 6
    }`

**Comment by komali2** [comment]
Seconded. Does not recognize the .jshintrc config option {`"esversion": 6}`

**Comment by renatomariscal** [comment]
A workaround, if your package doesn't depend on jshint directly, try adding it:
```bash
npm install jshint --save
```

**Comment by Gilwyad** [comment]
That workaround did not help me. This issue makes this extension unusable.

**Comment by RMacfarlane** [comment]
This extension doesn't ship with a version of jshint, it just uses what you have installed.

What's the output of running `npm outdated`? This prints packages that have newer versions. If you remember that you installed it globally, you can do `npm update -g jshint`. If it is local just `npm update jshint` (and then update your `package.json` file).

Support for `esversion` was released starting with jshint version [2.9.0](https://github.com/jshint/jshint/blob/d3d84ae1695359aef077ddb143f4be98001343b4/CHANGELOG.md#290-2015-09-03)
