### ISSUE TITLE
Is there something like "jshint.extract" : "auto" to mimic the behaviour of jshint --extract=auto ?

### ISSUE THREAD

**Issue by mateiacd** [Microsoft/vscode-jshint#44]
Hi,

What about the option to extract JavaScript code contained in an HTML file from VS Code ?

 Is there something like "jshint.extract" : "auto" to mimic the behaviour of jshint --extract=auto index.html ?

**Comment by RMacfarlane** [comment]
There is now a `jshint.lintHTML` option that when enabled, will run jshint on JS that's in script tags in HTML in version 0.10.16.
