### ISSUE TITLE
VS Code doesn't recognize jshint if installed globally via Yarn

### ISSUE THREAD

**Issue by reybango** [Microsoft/vscode-jshint#45]
OS: Win10 latest insider build
Code: v1.16.1
JSHint: v2.9.5 (installed globally)
JSHint Extenstion: 0.10.15

I installed JSHint globally using Yarn. It's accessible via commandline in cmd, git bash & WSL. Unfortunately VS Code doesn't seem to see it, throwing the following error within the editor:

> Failed to load jshint library. Please install jshint in your workspace folder using 'npm install jshint' or globally using 'npm install -g jshint' and then...

Uninstalling the Yarn version and reinstalling via npm globally fixes it with VS Code now seeing JSHint.

Not sure if it's a bug or a config issue.

Would love some help since we'd like to use Yarn.

**Comment by egamma** [comment]
@reybango this is this issue https://github.com/Microsoft/vscode-eslint/issues/187 which requires some support from yarn.

**Comment by dbaeumer** [comment]
@reybango alternatively you can install jshint locally in your workspace (which is the recommended way anyways). If installed locally you can use yarn without problems.

**Comment by RMacfarlane** [comment]
Added `jshint.packageManager` setting which can be either `npm` or `yarn` in version 0.10.17. When this is set to `yarn`, the extension looks for the jshint in the global yarn dir if it can't be found locally.
