### ISSUE TITLE
jshint.exclude for internal paths

### ISSUE THREAD

**Issue by Spown** [Microsoft/vscode-jshint#46]
because [this issue](/Microsoft/vscode/issues/24033) will probably take literally years to resolve (it's been baried in the backlog for months now) I thought I could find a workaround and ignore the faulty files for this extension. Yet, no matter what glob I try I can't seem do it, probably because of the pattern relativity to the Workroot (#28) and the "file's" path starting with "git:/" which doesn't map to anything. I don't even know what the "real" path is:
![](https://drive.google.com/uc?id=0B-OJBofmehO3cDRvNFphMUpqWW8)
I tried everything
```
*.js.git
**.js.git
**/*.js.git
**/**.js.git
**/*.js.git*
**/*.js.git**
**/**.js.git**
```
tried both with ``/`` and ``\\``. 

I know it's technically not your bug, but I would be very grateful if you could help. Incorporating an internal filter that only allows actual existent files to be linted wouldn't harm to have anyway. Or maybe at least writable files (these .js.git things are readonly) so that new not yet saved files could be still linted. 

Thank you.

**Comment by RMacfarlane** [comment]
@Spown I just checked in a fix for this. I'll publish a new version of the extension by the end of the week

**Comment by RMacfarlane** [comment]
Version 0.10.17 is published
