### ISSUE TITLE
jshint: Incompatible values for the 'esversion' and 'esnext' linting options

### ISSUE THREAD

**Issue by darrenbrett** [Microsoft/vscode-jshint#49]
JSHint options set up in workspace settings are incompatible.

I have this in my workspace settings:

```
{
  "jshint.enable": true,
  "jshint.options": {
  "esversion": 6, 
  "esnext": true, 
  "moz": true}
}
```

I have "esnext" set to "true" here because I want to be able to use async/await in Node. But in my individual files I then get this message:

> [jshint] Incompatible values for the 'esversion' and 'esnext' linting options. (0% scanned). (E059)

**Comment by RMacfarlane** [comment]
`esnext` is being deprecated in favor of `"esversion": 6`: http://jshint.com/docs/options/#esnext
Try using only `"esversion": 6`

**Comment by Quper24** [comment]
> `esnext` is being deprecated in favor of `"esversion": 6`: http://jshint.com/docs/options/#esnext
> Try using only `"esversion": 6`

not support async await
