### ISSUE TITLE
Navigating from and to a file stacks the errors instead of overwriting the same error.

### ISSUE THREAD

**Issue by janpieterz** [Microsoft/vscode-jshint#5]
When navigating from and to a file (without opening it in working files) the errors stack, as shown in the screenshot below.

This behavior isn't present when the file is in working files, only when browsing in and out (taking a peek).

![image](https://cloud.githubusercontent.com/assets/383634/11400691/1550929e-938f-11e5-8838-3916e7870e0a.png)

**Comment by dbaeumer** [comment]
This issue was moved to Microsoft/vscode#814
