### ISSUE TITLE
Failed to load jshint library. Please install jshint .... even after installing jshint

### ISSUE THREAD

**Issue by KaushalyaPradeep** [Microsoft/vscode-jshint#50]
I get following error when I am opening vscode.

`Failed to load jshint library. Please install jshint in your workspace folder using 'npm install jshint' or globally using 'npm install -g jshint' and then press Retry.`

even after installing jshint globally like `sudo npm install -g jshint`
```
which jshint
/usr/bin/jshint
```

But I do get the hints  with the bulb symbol when I highlight my JavaScript code.
I am using a Linux Mint 18.3 system.

Please help

**Comment by RMacfarlane** [comment]
What was the result of trying to install without `sudo`? A permissions error? What's the output of `npm config get prefix`? VSCode looks for globally installed npm packages in the result of `npm config get prefix` + `lib/node_modules` on Linux

**Comment by KaushalyaPradeep** [comment]
With sudo there was a permission(write) error. 
`npm config get prefix` gave me the output `/usr`
How could I fix this?

**Comment by RMacfarlane** [comment]
[This](https://docs.npmjs.com/getting-started/fixing-npm-permissions) page describes two possible solutions for fixing the permissions error. Doing that and then reinstalling the package should get it working.

You could also try just manually setting the prefix value. `npm ls -g --depth=0` will print the path to the node_modules folder jshint was installed to. `npm config edit` and then find the line with `prefix=/usr` and edit it to be the path to your node_modules folder, without the `/lib` segment at the end

**Comment by KaushalyaPradeep** [comment]
Thanks @RMacfarlane  I fixed the permission error by installing Node via NVM. Now it works fine. No errors.
