### ISSUE TITLE
how to this...?

### ISSUE THREAD

**Issue by BVJeon** [Microsoft/vscode-jshint#51]
OMG... Help me please.

I use React-Native with JSHint 
But! See error. 
I did Google search. Through the setup, the grammar of es was also applied. But there is an error.

Issues found : https://github.com/Microsoft/vscode-jshint/issues/29

![2018-02-07 6 48 32](https://user-images.githubusercontent.com/33533201/35909656-9b593fc6-0c37-11e8-8abb-1e76159e33fc.png)
![2018-02-07 6 50 38](https://user-images.githubusercontent.com/33533201/35909744-d26babf2-0c37-11e8-88aa-7216351f36bb.png)
![2018-02-07 6 50 59](https://user-images.githubusercontent.com/33533201/35909758-dc02404a-0c37-11e8-883a-000eae0e205e.png)

**Comment by RMacfarlane** [comment]
JSHint can't parse JSX syntax, but the extension is running JSHint on the entire file, so it is erroring on the JSX syntax. This is a bug that isn't easy to fix, but as a workaround for now you could use `/* jshint ignore:start */` and `*/ jshint ignore:end */` above and below the render method.

`type Props = {};` looks like Typescript to me, should this be a `.tsx` file?

**Comment by BVJeon** [comment]
This file is React-Native example file and "*.js/javascriptreact".

I see. I use /* jshint ignore:start */ and */ jshint ignore:end */ above and below the render method.

type Props = {};
Let's find another solution to this. 

Thank you so much for answering. :)
Have a nice day~~~

**Comment by BVJeon** [comment]
And although there is still a bug(*JSX Parsing bug) left, I will close this issue.
