### ISSUE TITLE
How to install

### ISSUE THREAD

**Issue by jrock2004** [Microsoft/vscode-jshint#56]
Is this plugin installed by default? When I search for `jslint` I get some other persons plugin.

**Comment by RMacfarlane** [comment]
@jrock2004 Do you mean how to install this extension to VS Code, or how to install the `jshint` package?

`jshint` isn't installed by default with the extension, so you would need to follow the steps in the [README](https://github.com/Microsoft/vscode-jshint/blob/master/README.md). `jshint` and `jslint` are two different JavaScript linters, `jshint` is a fork of `jslint` meant to be more configurable and community-driven.

**Comment by jrock2004** [comment]
The plugin. I have jshint installed via `yarn global add jslint`

**Comment by RMacfarlane** [comment]
This is the extension for integrating jsHint into VSCode, not jsLint. If this is the JS linter you're looking for, it should be the first result when you search for `jshint` in the extensions panel.
![screen shot 2018-03-30 at 3 54 01 pm](https://user-images.githubusercontent.com/3672607/38156426-a075aa8a-3432-11e8-89cf-0295e992beba.png)

If you're looking for a jsLint extension, I think you want this one: https://github.com/ajhyndman/vscode-jslint
For either, there should be an install button from that view where "Disable" is currently shown in the screenshot

**Comment by jrock2004** [comment]
User error. I was search for `jslint` not `jshint`
