### ISSUE TITLE
Failed to install dbaeumer.jshint

### ISSUE THREAD

**Issue by premedios** [Microsoft/vscode-jshint#57]
I updated VSCode yesterday and I have been getting the above message everytime I tried to reinstall this plugin. Before I would get the message:
```
Failed to update dbaeumer.jshint
```
I uninstalled the extension hoping that the reinstall would work but it didn't. I tried to install it manually but it complained about the .vsix file being corrupt.

**Comment by RMacfarlane** [comment]
Thanks for reporting. What OS are you using? Can you run the `Developer: Toggle Developer Tools` action when this happens and see if there is an error printed to the console?

**Comment by premedios** [comment]
The first time this error was when I was trying to update the extension after the vscode update two days ago. The console was complaining about the extension's dot folder not being empty so I deleted that folder and I was able to reinstall the extension. Next time I get this error on any extension's update or installation I'll use the tip you stated in your response. Thanks.

**Comment by RMacfarlane** [comment]
Closing this out, please file a new issue if you see this again
