### ISSUE TITLE
Request initialize failed with message: missing ) after argument list

### ISSUE THREAD

**Issue by DoubleCouponDay** [Microsoft/vscode-jshint#63]
this error is produced after restarting vsc with jshint installed, and installing jshint as an npm global.

**Comment by RMacfarlane** [comment]
@DoubleCouponDay Thanks for reporting this. Could you also include this information?

- Extension version
- VSCode version
- Result of running `npm config get prefix` and `npm ls -g --depth=0`

**Comment by DoubleCouponDay** [comment]
visual studio code version: 1.25.1
jshint extension version: 0.10.19
jshint global version: 2.9.5
**`npmconfig get prefix`:** C:\Users\sjsui\AppData\Roaming\npm
**`npm ls -g --depth=0` :** 
```C:\Users\sjsui\AppData\Roaming\npm
+-- @warriorjs/cli@0.5.1
+-- babel-cli@6.26.0
+-- babel-eslint@8.2.2
+-- babel-preset-env@1.7.0
+-- browserify@16.2.2
+-- brunch@2.10.12
+-- eslint@5.0.1
+-- eslint-config-defaults@9.0.0
+-- eslint-plugin-react@7.10.0
+-- grunt-cli@1.2.0
+-- grunt-steal@1.0.0
+-- jasmine@3.0.0
+-- jshint@2.9.5
+-- jslint@0.12.0
+-- npm@6.2.0
+-- parcel-bundler@1.8.1
+-- tslint@5.10.0
+-- typescript@2.9.2
`-- uglify-js@3.4.2
```

**Comment by DoubleCouponDay** [comment]
screenshot: 
![image](https://user-images.githubusercontent.com/7555725/43230203-8868ac54-90bb-11e8-9bb0-8cb9b1a0893a.png)

**Comment by DoubleCouponDay** [comment]
output window:
![image](https://user-images.githubusercontent.com/7555725/43230570-e3c47866-90bc-11e8-8272-2ded4df2ec10.png)

**Comment by tahsincange** [comment]
Same error here. (Its a fresh windows installation)

My infos :
VSCode version 1.27.2
JSHint Extension version: 0.10.20
JSHint Global version: 2.9.6

``npm config get prefix`` : ``C:\Users\tcgenc\Applications\node``

``npm ls -g --depth=0`` :

``C:\Users\tcgenc\Applications\node
+-- jshint@2.9.6
+-- lma@1.0.2 -> C:\Users\tcgenc\Repos\ls-for-win
+-- npm@6.4.1
+-- path-intellisense@1.4.2 -> C:\Users\tcgenc\.vscode\extensions\christian-kohler.path-intellisense-1.4.2
+-- yarn@1.9.4
`-- yo@2.0.5``

**Comment by tahsincange** [comment]
Detailed error on logs :

`[2018-09-28 08:27:50.980] [renderer1] [error] Request initialize failed with message: missing ) after argument list: Error: Request initialize failed with message: missing ) after argument list
    at new ResponseError (C:\Users\tcgenc\.vscode\extensions\dbaeumer.jshint-0.10.20\jshint\node_modules\vscode-jsonrpc\lib\messages.js:46:28)
    at handleResponse (C:\Users\tcgenc\.vscode\extensions\dbaeumer.jshint-0.10.20\jshint\node_modules\vscode-jsonrpc\lib\main.js:430:48)
    at processMessageQueue (C:\Users\tcgenc\.vscode\extensions\dbaeumer.jshint-0.10.20\jshint\node_modules\vscode-jsonrpc\lib\main.js:258:17)
    at Immediate._onImmediate (C:\Users\tcgenc\.vscode\extensions\dbaeumer.jshint-0.10.20\jshint\node_modules\vscode-jsonrpc\lib\main.js:242:13)
    at runCallback (timers.js:789:20)
    at tryOnImmediate (timers.js:751:5)
    at processImmediate [as _immediateCallback] (timers.js:722:5)`

**Comment by tahsincange** [comment]
I solved it. It happens because it cant found node folder path on `extension.js:42` . Just set nodePath in jshint settings and its works like a charm.

PS: It cant find my node path because of i installed node on user not system.
