### ISSUE TITLE
Allow use of spread/rest operator

### ISSUE THREAD

**Issue by stefanuddenberg** [Microsoft/vscode-jshint#67]
The [latest version of jshint](https://jshint.com/blog/2019-02-05/release-2-10-0/) now allows for the use of the `...` spread/rest operator without warnings. I know that my jshint is up to date, but with the extension I still can't get the operator to work without warnings or wrapping the line with `ignore` statements. Changing `esversion` in settings to `9` doesn't help. Is there something I am missing, or does the extension tap into its own (outdated) version of jshint?

**Comment by stefanuddenberg** [comment]
For some reason changing to `esversion: 9` in config now helps, even though the config file complains about `9` being an invalid setting...

**Comment by RMacfarlane** [comment]
The extension doesn't ship with a version of `jshint`, but it does use a schema from https://github.com/SchemaStore/schemastore to validate the config file. That's out of date so I've sent a PR to update it. Thanks!

**Comment by RMacfarlane** [comment]
Should be fixed with https://github.com/SchemaStore/schemastore/commit/494a7f343a1f52713efa0682594db30f784450c6
