### ISSUE TITLE
globals attribute in package.json not recognized by JSHint

### ISSUE THREAD

**Issue by s3anmorrow** [Microsoft/vscode-jshint#68]
Love this extension - have my entire group of students using it. 

But the globals attribute in package.json doesn't seem to be working:
"jshintConfig": {
  "esversion": 6,
  "strict": "implied",
  "browser": true,
  "devel": true,
  "node": true,
  "globals": {
    "Headers": true
}
Headers will still be flagged by JSHint as undefined

/* globals Headers */ at top is a workaround (or including a .jshintrc)
Am I overlooking something?

Thanks in advance!

**Comment by RMacfarlane** [comment]
That config looks right to me. Can you open the output panel is VSCode and select `jshint` from the dropdown and paste any text from there?

<img width="1128" alt="screen shot 2019-02-12 at 9 29 50 am" src="https://user-images.githubusercontent.com/3672607/52655338-ca9a3d00-2ea8-11e9-8905-7dfc5f5b2a3d.png">

**Comment by s3anmorrow** [comment]
Sure thing - jshint certainly is reading from package.json... but globals seems to be ignored, maybe?

![screen shot 2019-02-12 at 1 41 19 pm](https://user-images.githubusercontent.com/5539774/52656054-ef53dc00-2ecb-11e9-97a6-3bafde05cfdd.png)

Any other thoughts? Thanks in advance!

**Comment by RMacfarlane** [comment]
Hmm. What version of `jshint` are you using? Could you also include the error message you're seeing for `Headers`?

**Comment by s3anmorrow** [comment]
Version: jshint@2.10.1
Error message - 'Headers' is not defined. (W117)
Never had a problem when using .jshintrc :(

package.json:
> {
  "name": "sass-babel-with-gulp-nscc",
  "version": "1.0.0",
  "description": "Starter template for an ES2015 app implementing Sass/Babel and Gulp",
  "main": "app.js",
  "author": "Sean Morrow / NSCC Truro Campus",
  "license": "",
  "dependencies": {},
  "devDependencies": {
    "gulp": "^3.9.1",
    "gulp-concat": "^2.6.0",
    "gulp-sass": "^3.1.0",
    "gulp-sourcemaps": "^2.6.0",
    "merge-stream": "^1.0.0",
    "babelify": "^7.3.0",
    "babel-core": "^6.26.3",
    "babel-preset-env": "^1.7.0",
    "browserify": "^12.0.2",
    "vinyl-buffer": "^1.0.0",
    "vinyl-source-stream": "^1.1.0",
    "gulp-webserver": "^0.9.1"
  },
  "browserify": {
    "transform": [
      [
        "babelify",
        {
          "presets": [
            "env"
          ]
        }
      ]
    ]
  },
  "jshintConfig": {
    "esversion": 6,
    "strict": "implied",
    "browser": true,
    "devel": true,
    "node": true,
    "globals": {
      "Headers": false  
    }
  }
}

**Comment by RMacfarlane** [comment]
Sorry for the delay in looking at this!

I think the issue is that the extension isn't listening for updates to the `package.json` file. I see the same error when I add something to globals for the first time, but not after reloading VSCode. The extension does correctly listen for changes to `.jshintrc` files.

Thanks for catching this, I'll prepare a fix!

**Comment by s3anmorrow** [comment]
Awesome – glad I could help!
Thanks Rachel :)

Sean Morrow
Faculty
IT Web Programming / Game Development
Nova Scotia Community College
902.893.7891
@s3anmorrow
www.seanmorrow.ca
