### ISSUE TITLE
Add support to external .jshintrc file

### ISSUE THREAD

**Issue by fsmaia** [Microsoft/vscode-jshint#7]
As in "jscs.preset", it would be nice to have support for a external .jshintrc file. I see that putting the file directly in project is widely recommended, but there are some scenarios in which .jshintrc must be apart. I thought that this feature was covered by "extend" inside "jshint.options" but doesn't seem to work.

**Comment by smorhaim** [comment]
+1

Atom and others support reading the rc file in the project.

**Comment by marioestrada** [comment]
Have you tried using:

```
"jshint.options": {
  "config": "/path/to/.jshint"
}
```

**Comment by fsmaia** [comment]
It works @marioestrada! Big thanks!
