### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by uryu-myao** [Microsoft/vscode-jshint#70]
- Issue Type: `Performance`
- Extension Name: `jshint`
- Extension Version: `0.10.20`
- OS Version: `Darwin x64 18.0.0`
- VSCode version: `1.31.0`

:warning: Make sure to **attach** this file from your *home*-directory: `/Users/econosys/dbaeumer.jshint-unresponsive.cpuprofile.txt` :warning:

Find more details here: https://github.com/Microsoft/vscode/wiki/Explain:-extension-causes-high-cpu-load

**Comment by RMacfarlane** [comment]
Hey @uryu-myao, thanks for reporting this. Can you attach the file `/Users/econosys/dbaeumer.jshint-unresponsive.cpuprofile.txt`?

**Comment by uryu-myao** [comment]
@RMacfarlane I fixed the error by updating vscode. Thanks anyway!
