### ISSUE TITLE
eversion 8 not accepted? 

### ISSUE THREAD

**Issue by rchrdnsh** [microsoft/vscode-jshint#74]
like the issue says. Trying to change the JSHint version to 8 and it says that only 3 5 and 6 are accepted?

**Comment by darrenbrett** [comment]
I'm running into the very same problem. According to the default documentation (https://jshint.com/docs/options/) we should be able to enable versions 8 or 9. But in my `settings.json` file, I get a green squiggly under `9`, and when hovered over it reads:

The ECMAScript version to which the code must adhere

Value is not accepted. Valid values: 3, 5, 6.

My full settings.json file looks like this:

{
  "jshint.enable": true,
  "jshint.options": {
    "esversion": 9,
    "moz": true,
    "supernew": true
  },
  "git.ignoreLimitWarning": true,
  "editor.tabSize": 2,
  "editor.detectIndentation": false,
  "editor.formatOnSave": true,
  "prettier.printWidth": 300,
  "javascript.suggestionActions.enabled": false,
  "workbench.colorCustomizations": {
    "tab.unfocusedActiveBorder": "#fff0"
  }
}

**Comment by stormwild** [comment]
Same here:

![Screen Shot 2019-07-27 at 3 55 19 PM](https://user-images.githubusercontent.com/657249/61991705-0a379880-b087-11e9-9f1b-60ae9a827625.png)

**Comment by RMacfarlane** [comment]
Thanks for reporting this! This should be fixed in the newest version of the extension, 0.10.21.
