### ISSUE TITLE
Where's the installer link?

### ISSUE THREAD

**Issue by coolaj86** [microsoft/vscode-jshint#89]
This project doesn't have a project URL set and no where in the README does it direct me to where I need to go to install this plugin.

**Comment by coolaj86** [comment]
When I google "VSCode JSHint" I get ***this*** repo as well as this landing page:
https://marketplace.visualstudio.com/items?itemName=dbaeumer.jshint

I think that's also the one that is recommended by VSCode itself.

Tt's not clear to me whether or not they are related, but I don't see any option in the VSCode Marketplace that looks like ***this*** repo (i.e. by Microsoft):
https://marketplace.visualstudio.com/search?term=jshint&target=VSCode&category=Linters&sortBy=Relevance

**Comment by RMacfarlane** [comment]
Hi @coolaj86! I've just updated the "About section" of the repo to link to https://marketplace.visualstudio.com/items?itemName=dbaeumer.jshint

These are indeed the same project, the extension was originally published by a member of the VSCode team a long time ago. I'm not sure what's involved in changing the publisher
